# Generated by Django 3.2.14 on 2022-09-02 05:16

from django.db import migrations, models, ProgrammingError

def run_migration(apps, schema_editor):
    try:
        migrations.RemoveField(
            model_name='raumliste',
            name='raum_id',
        ),
        
    except ProgrammingError as e:  # sometimes it can exist
        if "already exists" not in str(e):
            raise
        
    try:
        
        migrations.AddField(
            model_name='geraete',
            name='connection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='geraete',
            name='hw_hersteller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='geraete',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='geraete',
            name='ip_port',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='geraete',
            name='put_request',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='raumliste',
            name='id',
            field=models.AutoField(db_column='Id', default=0, primary_key=True, serialize=False),
        ),
    except ProgrammingError as e:  # sometimes it can exist
        if "already exists" not in str(e):
            raise
    
    

class Migration(migrations.Migration):

    dependencies = [
        ('ki_energie', '0012_auto_20220901_1820'),
    ]
    

    operations = [
        migrations.RunPython(run_migration),
    ]
